#!/usr/bin/env python3
"""gen_docs.py - generated reference docs, never hand-written.

Produces two files from the ratified sources (agent SKILL.mds, playbook
SKILL.mds, routes.json):

  JOB_DESCRIPTIONS.md - one entry per agent: type, role, job components,
      edges, tuple count. Extracted verbatim from each agent's ratified
      SKILL.md - this file adds an index, never new claims.
  PLAYBOOKS.md - one entry per playbook: trigger, agents deployed,
      description, HITL gates. Extracted from each playbook's SKILL.md.

Hand-edits to the OUTPUT files are a defect (same rule as SWARM.md);
edit the sources and regenerate. Run from the blueprint root; copy the
outputs into listing-agents/docs/ via the same discipline as sync_core.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))


def frontmatter_desc(text: str) -> str:
    m = re.search(r'^description:\s*"(.*?)"\s*$', text, re.M)
    return m.group(1) if m else "(no description in frontmatter)"


def section(text: str, header: str) -> str:
    """Return the body of a '## <header>' section, stripped."""
    m = re.search(rf'^##+\s*(?:\d+\.\s*)?{re.escape(header)}\s*$(.*?)(?=^##|\Z)',
                  text, re.M | re.S)
    return m.group(1).strip() if m else ""


def agent_dirs():
    out = []
    for d in sorted(os.listdir(ROOT)):
        if re.match(r'^\d{2}-', d) and os.path.isdir(os.path.join(ROOT, d)):
            out.append(d)
    return out


def gen_job_descriptions() -> str:
    routes = json.load(open(os.path.join(ROOT, "identity", "routes.json")))
    sends, receives = {}, {}
    for r in routes["routes"]:
        for s in r["senders"]:
            sends.setdefault(s, set()).add(r["intent"])
        for t in r["receivers"]:
            receives.setdefault(t, set()).add(r["intent"])

    parts = ["""# JOB_DESCRIPTIONS.md (GENERATED - do not hand-edit)

Generated by gen_docs.py from each agent's ratified SKILL.md and
identity/routes.json. One entry per agent: what it is, what it does,
what it sends and receives, and how many predeliberated tuples govern
it. The SKILL.md and DECISIONS.md in each agent's directory remain the
full ratified sources; this file is the index a human reads first.
"""]
    for d in agent_dirs():
        num = d.split("-")[0]
        skill = open(os.path.join(ROOT, d, "SKILL.md")).read()
        dec_path = os.path.join(ROOT, d, "DECISIONS.md")
        n_tuples = 0
        if os.path.exists(dec_path):
            n_tuples = sum(1 for line in open(dec_path)
                           if line.startswith("- ("))
        title = re.search(r'^# (.+)$', skill, re.M)
        typ = re.search(r'\*\*Type:\*\*\s*(.+)$', skill, re.M)
        role = section(skill, "Role") or section(skill, "1. Role")
        components = section(skill, "Job Components")
        parts.append(f"""## {title.group(1) if title else d}

**Type:** {typ.group(1).strip() if typ else "(unspecified)"}
**Summary:** {frontmatter_desc(skill)}
**Sends:** {", ".join(sorted(sends.get(num, []))) or "(none routed)"}
**Receives:** {", ".join(sorted(receives.get(num, []))) or "(none routed)"}
**Predeliberated tuples:** {n_tuples} (see {d}/DECISIONS.md)

{role}

### Job components
{components or "(see SKILL.md)"}
""")
    return "\n".join(parts)


def gen_playbooks() -> str:
    pb_root = os.path.join(ROOT, "playbooks")
    parts = ["""# PLAYBOOKS.md (GENERATED - do not hand-edit)

Generated by gen_docs.py from each playbook's ratified SKILL.md. One
entry per playbook: trigger, agents deployed, gates. Each playbook's
own SKILL.md remains the full ratified source with the step tables;
this file is the breakdown a human reads first.
"""]
    for d in sorted(os.listdir(pb_root)):
        p = os.path.join(pb_root, d, "SKILL.md")
        if not os.path.isfile(p):
            continue
        text = open(p).read()
        title = re.search(r'^# (.+)$', text, re.M)
        trigger = section(text, "Trigger")
        gates = section(text, "HITL gates (hard stops, not judgment calls)") \
            or section(text, "HITL gates")
        desc = frontmatter_desc(text)
        agents = sorted(set(re.findall(r'\b(\d{2})\b(?=\s*[|→])', text)))
        parts.append(f"""## {title.group(1) if title else d}

**Summary:** {desc}
**Agents touched (from step tables):** {", ".join(agents) or "(see SKILL.md)"}

### Trigger
{trigger or "(see SKILL.md)"}

### HITL gates
{gates or "(none listed beyond swarm-wide gates)"}
""")
    return "\n".join(parts)


def main():
    jd = gen_job_descriptions()
    pb = gen_playbooks()
    open(os.path.join(ROOT, "JOB_DESCRIPTIONS.md"), "w").write(jd)
    open(os.path.join(ROOT, "PLAYBOOKS.md"), "w").write(pb)
    print(f"wrote JOB_DESCRIPTIONS.md ({len(jd.splitlines())} lines), "
          f"PLAYBOOKS.md ({len(pb.splitlines())} lines)")


if __name__ == "__main__":
    sys.exit(main())
